version: "3.0"
services:
  scikit-learn:
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      MODULE_NAME: "scikit-learn"
      MODULE_TYPE: "Processing"
      INGRESS_HOST: "0.0.0.0"
      INGRESS_PORT: "80"
      EGRESS_URLS: "https://testdockercompose.free.beeceptor.com"
      MODEL_DOWNLOAD_URL: "https://drive.google.com/uc?export=download&id=1-abcdefgh"
      MODEL_FILEPATH:
      ORDERED_LABELS: "spend, administration, marketing_spend, florida, new_york"
      OUTPUT_LABEL: "prediction"
    ports:
      - 80:80
